createRootTemplate() -> createDirectoryTemplate(rootContext) -> DirectoryTemplate

templateType: "TemplateType" {
  shape: hexagon
}

DirectoryTemplate -> list()

list() -> templateType

templateType -> directory -> createDirectory(templateContext)
templateType -> file

explanation: |md
  ```ts
    directoryTemplate.files.forEach(fileName => {
      const context = createContext(fileName);
      if
    });


    class DirectoryTemplate {
      generate() {
        // take the first node
        const node = this.nodes.pop();

        
      }
    }
  ```
|