on:
  release: 
    types: published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: bun install
      - run: bun build
      - run: |
          cd ./dist
          ls
          echo "npm publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}