on:
  pull_request:  

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: bun install
        name: Install
      - run: bun test
        name: Test
      - run: bun run build
        name: Build